# Generated by Django 3.2.20 on 2024-08-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_1', models.CharField(max_length=200)),
                ('texto_2', models.CharField(max_length=200)),
            ],
        ),
    ]
