# Generated by Django 4.2.3 on 2024-03-31 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="make",
            name="name",
            field=models.CharField(
                help_text="Enter a make (e.g. Yamaha)",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Make must be greater than 1 character"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="model",
            field=models.CharField(
                help_text="Enter a model (e.g. YZ 250FX)",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Model must be greater than 1 character"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.PositiveIntegerField(
                help_text="Enter a year (e.g. 1995)", unique=True
            ),
        ),
    ]
