# Generated by Django 4.2.7 on 2024-04-25 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_make_name_alter_model_model_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(help_text='Enter a segment (e.g. Off-Road, Trail..)', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Segment must be greater than 1 character')])),
            ],
        ),
    ]
