# Generated by Django 4.2.7 on 2024-04-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='name',
            new_name='make',
        ),
    ]
