# Generated by Django 4.2.7 on 2024-04-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_name_make_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='segment',
            field=models.ForeignKey(default=None , null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.segment'),
            preserve_default=False,
        ),
    ]
