# Generated by Django 4.2.7 on 2024-04-28 03:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_aplication_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aplication",
            name="segment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.segment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="segment",
            name="segment",
            field=models.CharField(
                blank=True,
                help_text="Enter a segment (e.g. Off-Road, Trail..)",
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, "Segment must be greater than 1 character"
                    )
                ],
            ),
        ),
    ]
