# Generated by Django 4.2.7 on 2024-05-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_category_subcategory_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the property name (e.g. Internal Diameter, External Diameter, Material)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Enter the value of the property (e.g. 50mm, Steel)', max_length=200)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='vehicles.part')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_properties', to='vehicles.property')),
            ],
        ),
    ]
