# Generated by Django 4.2.7 on 2024-06-09 02:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a category (e.g. Engine, Frame, Suspension)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Categories must be greater than 1 character')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vehicles.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vehicles.subcategory'),
        ),
    ]
