# Generated by Django 4.2.7 on 2024-06-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_alter_category_name_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory',
        ),
    ]
