# Generated by Django 4.2.7 on 2024-06-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_rename_name_category_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
    ]
