# Generated by Django 4.2.7 on 2024-07-05 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_aplication_market_aplicationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='sku',
            field=models.CharField(default='none', help_text='Enter de SKU', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'SKU must be greater than 1 character')]),
            preserve_default=False,
        ),
    ]
