# Generated by Django 4.2.7 on 2024-07-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_remove_part_subcategories_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partproperty',
            name='part',
        ),
        migrations.AddField(
            model_name='partproperty',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='partpropertycategory', to='vehicles.category'),
            preserve_default=False,
        ),
    ]
