# Generated by Django 3.2.20 on 2024-08-11 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0019_catproperty_delete_partproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('property', models.CharField(help_text='Enter the property name (e.g. Internal Diameter, External Diameter, Material)', max_length=100)),
                ('value', models.CharField(help_text='Enter the value of the property (e.g. 50mm, Steel)', max_length=200)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_partproperty_set', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='vehicles.part')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_partproperty_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CatProperty',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
