# Generated by Django 3.2.20 on 2024-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_auto_20240810_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
