# Generated by Django 3.2.20 on 2024-08-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_part_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partproperty',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='vehicles.part'),
        ),
    ]
