# Generated by Django 3.2.20 on 2024-08-26 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_alter_partproperty_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(db_index=True, help_text='Enter the general part name (e.g. Spark Plug)', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Part name must be greater than 1 character')]),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(db_index=True, help_text='Enter de SKU', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'SKU must be greater than 1 character')]),
        ),
    ]
