# Generated by Django 4.2.7 on 2024-06-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanagement.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMensualFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('proveedor', models.CharField(max_length=255)),
                ('modalidad', models.CharField(choices=[('Fiscal', 'Fiscal'), ('No Fiscal', 'No Fiscal')], max_length=10)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Bancarios', 'Bancarios'), ('Tarjetas de credito', 'Tarjetas de credito'), ('Sueldos y remuneraciones', 'Sueldos y remuneraciones'), ('Proveedores', 'Proveedores')], max_length=50)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanagement.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoPrevisionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('proveedor_cliente', models.CharField(max_length=255)),
                ('modalidad', models.CharField(choices=[('Fiscal', 'Fiscal'), ('No Fiscal', 'No Fiscal')], max_length=10)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_adeudado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanagement.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngresoCierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('proveedor_cliente', models.CharField(max_length=255)),
                ('modalidad', models.CharField(choices=[('Fiscal', 'Fiscal'), ('No Fiscal', 'No Fiscal')], max_length=10)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_adeudado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanagement.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EgresoPresupuestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('proveedor_cliente', models.CharField(max_length=255)),
                ('modalidad', models.CharField(choices=[('Fiscal', 'Fiscal'), ('No Fiscal', 'No Fiscal')], max_length=10)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_adeudado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanagement.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EgresoCierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('proveedor_cliente', models.CharField(max_length=255)),
                ('modalidad', models.CharField(choices=[('Fiscal', 'Fiscal'), ('No Fiscal', 'No Fiscal')], max_length=10)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_adeudado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashmanagement.sucursal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
